### ISSUE TITLE
"output_file.write error"  When  dealing special characters 

### ISSUE THREAD

**Issue by lovitus** [homeisfar/LinuxDir2HTML#7]
```
22:25:19 ----output_file.write error [D.p(["/mnt/qnap-down/rsync-lxb/downloads.freemdict.com/Language_Learning_Videos/Korean/韩语NO1/【韩国语】【新标准韩国语】课程/【标准韩国语】韩语语法及句子（TOPIK【初中高级】全部语法）【PDF+DOC】*0*1646190332","fmdl_readme.md.html*1219*1632830920","index.html*17634*1645944789","【标准韩国语】语法*400896*1603918423","初级韩国语语法.doc*540520*1603918424","韩国语口语入门.pdf*46393914*1603918447","韩国语实用语法pdf电*5615991*1603918428","韩语TOPIK高级语法.doc*294912*1603918425","韩语入门语法-终结\udce8\udcaf*5494980*1603918429","韩语考试的 100条 语\udce6*24576*1603918428",58784642,""])
]
22:25:19 ----output_file.write error [D.p(["/mnt/qnap-down/rsync-lxb/downloads.freemdict.com/Language_Learning_Videos/Korean/韩语NO1/【韩国语】【新标准韩国语】课程/【标准韩国语】标准韩国语1-3册【MP3】/标韩另版第一册MP3+课文/标准韩国语第一册mp3/13-17课*0*1646190396","016*2588163*1603918255","13-*2798849*1603918255","14-*4034499*1603918258","15-*1696515*1603918257","15\udce8*3915267*1603918258","16-*1557411*1603918259","16\udce8*3516963*1603918260","17-*6157347*1603918262","fmd.html*2948*1632830897","ind.html*19042*1646384829",26287004,""])
```

Thanks for this awesome package

**Comment by homeisfar** [comment]
I'm glad you like it! Unfortunately I don't think there's a fix for your issue. The output file is written with UTF-8 compatibility, and so it should handle any glyph. This means the file name has some character in it that cannot be represented in Python's understanding of UTF-8, which I am not sure what or how that might be. But the problem is likely internal to Python's library code combined with Linux having almost zero restrictions on what characters can be part of a file name.

You might be able to copy and paste the file's name into a text editor, then copy and paste it back to overwrite the file's current name. That's my best guess at solving your issue.

**Comment by Jarvis-3-0** [comment]
I have had a similar issue to this, running on a Linux NAS. Please forgive me if there are errors in terminology - I am not a coder and never used python!

The error occurs due to the \udce8 \udcaf \udce6 etc parts where the UTF-8 encoder cannot recognise how to encode these special characters (part of a surrogate code?). In my case these codes are where apostrophes ( ' ) or accented characters etc are supposed to be. I'm not sure what part of the script causes these codes to be generated in the first place and whether it can be better fixed in that part of the script?

The big issue for me is that there are a number of output_file.write errors occurring, resulting in those lines being omitted from the output file. This in turn messes up the tree structure when viewing the output file, as the folder line references no longer match up. The special character issue also exists with the original Snap2HTML, but where the file name containing it is does not exist at all in the tree structure (however the tree structure is correct)

My workaround is to modify line 212 of linuxdir2html.py from
`output_file = open(f'{title}.html', 'w', encoding="utf-8")`
to
`output_file = open(f'{title}.html', 'w', encoding="utf-8", errors='xmlcharrefreplace')`
It does not insert the correct special character, but puts in a � instead, but at least it generates all folders and files and a usable tree structure, without any output_file.write errors.

I'm not sure if this would also help to fix issues #5 and #6. It could be related

**Comment by lovitus** [comment]
> 

thanks for your solution, do you consider to submit a pull request to this project?

**Comment by homeisfar** [comment]
I'll give it a test within the next couple of days. If all seems well I'll also publish the update to pip. Thanks for looking into it!

**Comment by homeisfar** [comment]
I think your change is good. I also took the opportunity to fix another outstanding issue with quotes in file names.

Some subtle issues still exist that cannot be fully resolved without significantly breaking with the snap2html template, which I am willing to do and am tracking in https://github.com/homeisfar/LinuxDir2HTML/issues/8. The end result should be transparent to users, except that linuxdir2html will handle files more robustly. But that work will arrive later.

In the meanwhile, I'll publish the fixes for this issue, #5, and #6 hopefully by tonight.
